### ISSUE TITLE
Check for Remote Desktop Sharing being on/off

### ISSUE THREAD

**Issue by Mobmaker55** [sourque/aeacus#97]
How would I go about a check to see if Remote Desktop Sharing is on/off?

This is a Windows question as much as it is a aeacus question, I realize this.
Would it be possible to check for a change when the on/off switch is turned, or do I just have to score based on the services for RDP being disabled?

It's okay if it's the latter, however, the former would be much preferred.

**Comment by Altoid0** [comment]
Something like this should account for most ways a user can disable RDP, obviously to score the opposite just change the values to the opposite.

```toml
[[check]]
message = 'Remote Desktop protocol has been disabled'
points = 5
[[check.passoverride]]
type='RegistryKey'
arg1='HKLM\SYSTEM\CurrentControlSet\Control\Terminal Server\fDenyTSConnections '
arg2='1'
[[check.passoverride]]
type='UserRights'
arg1='Everyone'
arg2='SeDenyRemoteInteractiveLogonRight'
[[check.passoverride]]
type = 'ServiceStatus'
arg1 = 'TermService'
arg2 = 'Stopped'
arg3 = 'Disabled'
```
