### ISSUE TITLE
Software version number check

### ISSUE THREAD

**Issue by ShadowSchulme** [sourque/aeacus#98]
If I wanted to check to see if a person installed a newer version, of lets say notepad++, and use this image in the future. How can I score based off of a version + ? for example: the image has version 7.1, the newest version is 7.9 and lets say I always want it to score versions 7.9 and up, so I don't have to change it to the currently up-to-date version before I give someone else the image?

**Comment by Altoid0** [comment]
There are a couple of ways you can do this, however, both of the methods I use involve a bit of finesse. The first method involves checking to see if the initial (outdated) version of the application has been uninstalled and if the binary for the application still exists.

Method 1: 
```toml
[[check]]
message = 'Firefox has been updated'
points = 2
[[check.pass]]
type = 'PackageInstalledNot'
arg1 = 'Mozilla Firefox 72.0.2 (x64 en-US)'
[[check.pass]]
type = 'FileExists'
arg1 = 'C:\Program Files\Mozilla Firefox\firefox.exe'
```

When a user updates the application to a newer version the older version should no longer be installed on the system thus satisfying the first condition. However, we also need to make sure that the application still exists and or else the user could just uninstall the package to get the update point. And since as you stated, the versions change over time we cannot check for a static version number. Thus we use the 2nd condition to ensure that the main binary for the program still exists, meaning that the user probably updated the application. It is possible to downgrade the application and still get the point but I can't think of anyone in the right mind who would want to do that as opposed to just updating.

Method 2:
```toml
[[check]]
message = 'Notepad++ has been updated'
points = 3
[[check.pass]]
type = 'FileContainsNot'
arg1 = 'C:\Program Files\Notepad++\change.log'
arg2 = 'v7.6.6'
[[check.pass]]
type = 'FileExists'
arg1 = 'C:\Program Files\Notepad++\notepad++.exe'
```

This method is a bit more advanced and takes some investigation but essentially I'm checking the changelog file to see what version of notepad++ is installed and then ensuring that that version does not equal the old outdated one previously installed on the image. The 2nd check just ensures that the main binary for notepadd++ is still present, indicating that notepad++ is most likely installed. We need the 2nd check because otherwise a user could just delete the changelog file or uninstall notepad++ and the vulnerability would score.

Hopefully this helped.
